Map<String, List<String>> allCountryAndCityName = {
  "Afghanistan": [
    "Kabul",
    "Kandahar",
    "Herat",
    "Mazar-i-Sharif",
    "Jalalabad",
    "Ghazni",
    "Bamiyan",
    "Khost",
    "Baghlan",
    "Puli Khumri",
    "Farah",
    "Firozkoh",
    "Taluqan",
    "Jowzjan",
    "Nili",
    "Sharan",
    "Zaranj",
    "Kandahar",
    "Lashkar Gah",
    "Charikar",
    "Pul-e-Alam",
    "Mehtarlam",
    "Sar-e Pol",
    "Chaghcharan",
    "Sheberghan",
    "Maymana",
    "Asadabad",
    "Kunduz",
    "Takhar",
    "Balkh",
    "Andkhoy",
    "Bamyan",
    "Paktia",
    "Nangarhar",
    "Paktika",
    "Badakhshan",
    "Samangan",
    "Wardak",
    "Urozgan",
    "Daykundi",
    "Ghor",
    "Zabul",
    "Logar",
    "Nimroz",
    "Badghis",
    "Kapisa",
    "Panjshir",
    "Kunar",
    "Laghman",
    "Helmand",
    "Faryab"
  ],
  "Albania": [
    "Tirana",
    "Durrës",
    "Vlorë",
    "Shkodër",
    "Fier",
    "Saranda",
    "Korçë",
    "Gjirokastër",
    "Përmet",
    "Elbasan",
    "Kavajë",
    "Lushnjë",
    "Vau i Dejës",
    "Kamëz",
    "Bulqizë",
    "Përmet",
    "Rrogozhinë",
    "Cakran",
    "Patos",
    "Divjakë",
    "Fushë-Krujë",
    "Berat",
    "Dibër",
    "Krujë",
    "Mirditë",
    "Saranda",
    "Klos",
    "Peqin",
    "Tropojë",
    "Cakran",
    "Maliq"
  ],
  "Algeria": [
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Blida",
    "Batna",
    "Sétif",
    "Tlemcen",
    "Ouargla",
    "Biskra",
    "Bejaïa",
    "Tizi Ouzou",
    "Skikda",
    "El Oued",
    "Chlef",
    "Laghouat",
    "M'Sila",
    "Khenchela",
    "Saida",
    "Mostaganem",
    "Guelma",
    "Relizane",
    "El Tarf",
    "Médéa",
    "Tiaret",
    "Tipaza",
    "Adrar",
    "Ghardaïa",
    "Bordj Bou Arréridj",
    "Jijel",
    "Tamanghasset",
    "Illizi",
    "Mila",
    "Bouira",
    "El Bayadh",
    "Tamanrasset",
    "Tissemsilt",
    "Kouba",
    "Aïn Temouchent",
    "Sidi Bel Abbès",
    "Tizi Ouzou"
  ],
  "Andorra": [
    "Andorra la Vella",
    "Escaldes-Engordany",
    "Encamp",
    "La Massana",
    "Sant Julià de Lòria",
    "Andorra la Vella",
    "El Serrat",
    "Pas de la Casa",
    "Soldeu",
    "Ordino",
    "Canillo",
    "Sant Joan de Caselles",
    "Les Escaldes",
    "Arinsal",
    "Engordany",
    "Auvinyà",
    "La Cortinada",
    "Prats"
  ],
  "Angola": [
    "Luanda",
    "N'dalatando",
    "Lobito",
    "Huambo",
    "Malanje",
    "Kuito",
    "Cabinda",
    "Saurimo",
    "Menongue",
    "Lubango",
    "Sumbe",
    "Namibe",
    "Luena",
    "Cuito Cuanavale",
    "Benguela",
    "Catumbela",
    "Kwanza Norte",
    "Kwanza Sul",
    "Lunda Norte",
    "Lunda Sul",
    "Zaire",
    "Bie",
    "Cunene",
    "Moxico",
    "Cuando Cubango",
    "Uíge",
    "Namibe",
    "Malanje",
    "Cazenga",
    "Kilamba Kiaxi",
    "Viana",
    "Cacuaco",
    "Catumbela",
    "Chinguar"
  ],
  "Antigua and Barbuda": [
    "Saint John's",
    "All Saints",
    "Liberta",
    "Parham",
    "English Harbour",
    "Jolly Harbour",
    "Willikies",
    "Freetown",
    "Cedar Grove",
    "Bolans",
    "Five Islands Village",
    "Darkwood",
    "St. George's",
    "Saint Mary",
    "Saint Paul",
    "Saint Philip"
  ],
  "Argentina": [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "Tucumán",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Neuquén",
    "Corrientes",
    "Santiago del Estero",
    "Bahía Blanca",
    "San Luis",
    "Posadas",
    "Rio Cuarto",
    "Tigre",
    "Villa María",
    "Lomas de Zamora",
    "Avellaneda",
    "Quilmes",
    "Morón",
    "San Fernando del Valle de Catamarca",
    "Zárate",
    "San Nicolás de los Arroyos",
    "Campana",
    "Resistencia",
    "Rawson",
    "Comodoro Rivadavia",
    "Santa Rosa",
    "Gualeguaychú",
    "Paraná",
    "Junín",
    "Lanús",
    "Berazategui"
  ],
  "Armenia": [
    "Yerevan",
    "Gyumri",
    "Vanadzor",
    "Vagharshapat",
    "Hrazdan",
    "Artik",
    "Ararat",
    "Abovyan",
    "Dilijan",
    "Ijevan",
    "Kapan",
    "Goris",
    "Charentsavan",
    "Aparan",
    "Martuni",
    "Stepanakert",
    "Shiraz",
    "Byureghavan",
    "Artashat",
    "Sisian",
    "Masis",
    "Tashir",
    "Spitak",
    "Ashtarak",
    "Yeghvard",
    "Ashotzq",
    "Noyemberyan",
    "Kaghsi",
    "Talinn",
    "Tatev"
  ],
  "Australia": [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Canberra",
    "Hobart",
    "Darwin",
    "Newcastle",
    "Central Coast",
    "Wollongong",
    "Sunshine Coast",
    "Cairns",
    "Geelong",
    "Toowoomba",
    "Townsville",
    "Ballarat",
    "Bendigo",
    "Mackay",
    "Launceston",
    "Rockhampton",
    "Albury",
    "Coffs Harbour",
    "Shepparton",
    "Mildura",
    "Bunbury",
    "Mount Gambier",
    "Whyalla",
    "Nowra",
    "Port Macquarie",
    "Ipswich",
    "Wagga Wagga",
    "Lismore",
    "Coffs Harbour",
    "Maitland",
    "Tamworth",
    "Mudgee"
  ],
  "Austria": [
    "Vienna",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt",
    "Villach",
    "Wels",
    "St. Pölten",
    "Bregenz",
    "Leonding",
    "Feldkirch",
    "Traun",
    "Dornbirn",
    "Mistelbach",
    "Kapfenberg",
    "Braunau am Inn",
    "Amstetten",
    "Hallein",
    "Schwechat",
    "Vöcklabruck",
    "Wiener Neustadt",
    "Sankt Valentin",
    "Tulln",
    "Krems an der Donau",
    "Zeltweg",
    "Ried im Innkreis",
    "Gmunden",
    "Korneuburg",
    "Baden",
    "Langenlois",
    "Pöchlarn",
    "St. Johann im Pongau"
  ],
  "Azerbaijan": [
    "Baku",
    "Ganja",
    "Sumgayit",
    "Lankaran",
    "Mingachevir",
    "Lerik",
    "Shirvan",
    "Masalli",
    "Quba",
    "Shaki",
    "Qazakh",
    "Siyazan",
    "Khirdalan",
    "Goychay",
    "Naftalan",
    "Astara",
    "Barda",
    "Fizuli",
    "Yardimli",
    "Qabala",
    "Salyan",
    "Aghdam",
    "Goranboy",
    "Qusari",
    "Balakan",
    "Khshtak",
    "Tartar",
    "Agstafa",
    "Goychay",
    "Gakh",
    "Oghuz",
    "Zardab",
    "Sabirabad",
    "Kakh"
  ],
  "Bahamas": [
    "Nassau",
    "Freeport",
    "George Town",
    "Abaco",
    "Marsh Harbour",
    "Bimini",
    "Eleuthera",
    "Long Island",
    "San Salvador",
    "Cat Island",
    "Exuma",
    "Andros Town",
    "Harbour Island",
    "Spanish Wells",
    "Great Inagua",
    "Rum Cay",
    "Crooked Island",
    "Mayaguana",
    "Sandy Point",
    "Fresh Creek",
    "Nicholls Town",
    "Clifton Bay",
    "Rock Sound",
    "Arthur's Town"
  ],
  "Bahrain": [
    "Manama",
    "Muharraq",
    "Riffa",
    "Sitra",
    "Hamad Town",
    "Budaiya",
    "A'ali",
    "Busaiteen",
    "Isa Town",
    "Khamis",
    "Malkiya",
    "Saar",
    "Diraz",
    "Sanad",
    "Jaww",
    "Salmaniya",
    "Al Muharraq",
    "Al Qudaybiyah",
    "Al Hidd",
    "Al Janabiya"
  ],
  "Bangladesh": [
    "Dhaka",
    "Chittagong",
    "Khulna",
    "Rajshahi",
    "Barisal",
    "Sylhet",
    "Narayanganj",
    "Comilla",
    "Nashik",
    "Gazipur",
    "Brahmanbaria",
    "Tangail",
    "Pabna",
    "Mymensingh",
    "Noakhali",
    "Jessore",
    "Kishoreganj",
    "Rangpur",
    "Satkhira",
    "Cox's Bazar",
    "Netrakona",
    "Jamalpur",
    "Sherpur",
    "Chuadanga",
    "Magura",
    "Faridpur",
    "Manikganj",
    "Kushtia",
    "Patuakhali",
    "Panchagarh",
    "Bagerhat",
    "Thakurgaon",
    "Dinajpur",
    "Nilphamari",
    "Feni",
    "Shariatpur",
    "Cumilla",
    "Bandarban",
    "Lakshmipur",
    "Pirojpur",
    "Jhalokati"
  ],
  "Barbados": [
    "Bridgetown",
    "Speightstown",
    "Oistins",
    "Bathsheba",
    "Holetown",
    "Christ Church",
    "St. Michael",
    "St. James",
    "St. Philip",
    "St. George",
    "St. Lucy",
    "St. Thomas",
    "St. John",
    "St. Joseph",
    "Warrens",
    "Mullins",
    "Six Roads",
    "Black Rock",
    "Dover",
    "Bayswater"
  ],
  "Belarus": [
    "Minsk",
    "Gomel",
    "Mogilev",
    "Vitebsk",
    "Grodno",
    "Brest",
    "Bobruisk",
    "Baranovichi",
    "Barysaw",
    "Pinsk",
    "Zhodino",
    "Orsha",
    "Slutsk",
    "Salihorsk",
    "Svetlahorsk",
    "Molodechno",
    "Novopolotsk",
    "Lida",
    "Sukhary",
    "Brest",
    "Mahilyow",
    "Polotsk",
    "Dzerzhinsk",
    "Kletsk",
    "Slonim",
    "Rechitsa",
    "Vawkavysk",
    "Shchuchin",
    "Nesvizh",
    "Chervyen",
    "Barauliany",
    "Luninets",
    "Beshankovichy"
  ],
  "Belgium": [
    "Brussels",
    "Antwerp",
    "Ghent",
    "Bruges",
    "Namur",
    "Liège",
    " Leuven",
    "Mons",
    "La Louvière",
    "Tournai",
    "Charleroi",
    "Ostend",
    "Mechelen",
    "Sint-Niklaas",
    "Turnhout",
    "Herstal",
    "Beringen",
    "Ypres",
    "Kortrijk",
    "Beersel",
    "Dendermonde",
    "Knokke-Heist",
    "Schaerbeek",
    "Louvain-la-Neuve",
    "Hasselt",
    "Malines",
    "Genk",
    "Aalst",
    "Nivelles",
    "Hooglede",
    "Zaventem",
    "Tielt",
    "Oostende"
  ],
  "Belize": [
    "Belmopan",
    "Belize City",
    "San Ignacio",
    "Corozal Town",
    "Orange Walk Town",
    "Punta Gorda",
    "Dangriga",
    "Toledo",
    "Cayo",
    "La Inmaculada",
    "Benque Viejo del Carmen",
    "San Pedro",
    "Ambergris Caye",
    "Caye Caulker",
    "Placencia",
    "Hopkins",
    "Independence",
    "Maya Center",
    "Crooked Tree",
    "Forest Home"
  ],
  "Benin": [
    "Porto-Novo",
    "Cotonou",
    "Djougou",
    "Parakou",
    "Bohicon",
    "Ouidah",
    "Natitingou",
    "Abomey",
    "Savalou",
    "Zoume",
    "Tchaourou",
    "Bante",
    "Kandi",
    "Save",
    "Adjarra",
    "Agbangnizoun",
    "Sakete",
    "Allada",
    "Kétou",
    "Aplahoué",
    "Toffo",
    "Kouandé",
    "Covè",
    "Bohicon",
    "Dogbo",
    "Malanville",
    "Nikki",
    "Aplahoué",
    "Calavi"
  ],
  "Bhutan": [
    "Thimphu",
    "Phuentsholing",
    "Paro",
    "Punakha",
    "Wangdue Phodrang",
    "Bumthang",
    "Trongsa",
    "Trashigang",
    "Zhemgang",
    "Haa",
    "Samdrup Jongkhar",
    "Nganglam",
    "Gelephu",
    "Lhuntse",
    "Sarpang",
    "Jakar",
    "Kanglung",
    "Rudulph",
    "Ura",
    "Chhukha"
  ],
  "Bolivia": [
    "Sucre",
    "La Paz",
    "Santa Cruz de la Sierra",
    "Cochabamba",
    "Oruro",
    "Potosí",
    "Tarija",
    "El Alto",
    "Trinidad",
    "Beni",
    "Pando",
    "Riberalta",
    "Montero",
    "Villazón",
    "Cobija",
    "Catahuasi",
    "San Ignacio de Velasco",
    "Sacaba",
    "Quillacollo",
    "Achocalla",
    "Pampa del Infierno",
    "Yacuiba",
    "Camiri",
    "Huarina",
    "Colcapirhua",
    "Colquiri",
    "Coroico",
    "Mizque",
    "San Borja",
    "San Pedro",
    "Capinota",
    "Caranavi",
    "Concepción",
    "Puerto Suárez"
  ],
  "Bosnia and Herzegovina": [
    "Sarajevo",
    "Banja Luka",
    "Tuzla",
    "Zenica",
    "Mostar",
    "Brčko",
    "Doboj",
    "Cazin",
    "Bihać",
    "Goražde",
    "Livno",
    "Gradačac",
    "Srebrenik",
    "Jajce",
    "Bugojno",
    "Tuzla",
    "Travnik",
    "Kiseljak",
    "Zavidovići",
    "Tešanj",
    "Pale",
    "Visoko",
    "Bileća",
    "Rudo",
    "Čapljina",
    "Sokolac",
    "Lukovo Polje",
    "Nova Bila",
    "Kakanj",
    "Neum",
    "Hadžići"
  ],
  "Botswana": [
    "Gaborone",
    "Francistown",
    "Molepolole",
    "Maun",
    "Kasane",
    "Selibe Phikwe",
    "Lobatse",
    "Palapye",
    "Jwaneng",
    "Serowe",
    "Ghanzi",
    "Nyangabgwe",
    "Tonota",
    "Letlhakane",
    "Mahalapye",
    "Hukuntsi",
    "Mochudi",
    "Tshabong",
    "Orapa",
    "Duma Tau",
    "Gweta",
    "Shakawe",
    "Sowa Town",
    "Botswana",
    "Lentsweletau",
    "Molepolole",
    "Kanye",
    "Letlhakeng",
    "Lerala",
    "Mmankgodi"
  ],
  "Brazil": [
    "Brasília",
    "São Paulo",
    "Rio de Janeiro",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Goiânia",
    "Belém",
    "Porto Alegre",
    "Campinas",
    "São Luís",
    "Maceió",
    "Duque de Caxias",
    "Natal",
    "Teresina",
    "Campo Grande",
    "João Pessoa",
    "São Bernardo do Campo",
    "Jundiaí",
    "Osasco",
    "Sorocaba",
    "Ribeirão Preto",
    "Niterói",
    "Canoas",
    "Aracaju",
    "Joinville",
    "Belford Roxo",
    "Contagem",
    "Diadema",
    "Petrópolis",
    "Macapá",
    "Boa Vista",
    "Rio Branco",
    "Palmas",
    "Vitória",
    "São José dos Campos"
  ],
  "Brunei": [
    "Bandar Seri Begawan",
    "Kuala Belait",
    "Seria",
    "Tutong",
    "Bangar",
    "Lumut",
    "Batu Apoi",
    "Temburong",
    "Jerudong",
    "Gadong",
    "Kiulap",
    "Rimba",
    "Berakas",
    "Muara",
    "Simpang 139",
    "Labi"
  ],
  "Bulgaria": [
    "Sofia",
    "Plovdiv",
    "Varna",
    "Burgas",
    "Ruse",
    "Stara Zagora",
    "Pleven",
    "Sliven",
    "Dobrich",
    "Shumen",
    "Pernik",
    "Haskovo",
    "Yambol",
    "Gabrovo",
    "Blagoevgrad",
    "Veliko Tarnovo",
    "Montana",
    "Vratsa",
    "Kardzhali",
    "Asenovgrad",
    "Kostinbrod",
    "Svishtov",
    "Razgrad",
    "Silistra",
    "Novi Pazar",
    "Targovishte",
    "Krumovgrad",
    "Petrich",
    "Devnya",
    "Chepelare",
    "Bansko"
  ],
  "Burkina Faso": [
    "Ouagadougou",
    "Bobo-Dioulasso",
    "Koudougou",
    "Manga",
    "Ouahigouya",
    "Fada N'gourma",
    "Banfora",
    "Dori",
    "Tenkodogo",
    "Ziniaré",
    "Tua",
    "Kaya",
    "Houndé",
    "Pama",
    "Daloa",
    "Orodara",
    "Yako",
    "Bittou",
    "Zorgho",
    "Sapouy",
    "Nouna",
    "Koupéla",
    "Toma",
    "Léo",
    "Koudougou",
    "Gaoua",
    "Sindou",
    "Dédougou",
    "Tchibanga",
    "Nongr-Massom"
  ],
  "Burundi": [
    "Gitega",
    "Bujumbura",
    "Ngozi",
    "Mwaro",
    "Cibitoke",
    "Kayanza",
    "Muramvya",
    "Ruyigi",
    "Bururi",
    "Makamba",
    "Karusi",
    "Bubanza",
    "Rumonge",
    "Mairie de Bujumbura",
    "Ntega",
    "Kigutu",
    "Mishasha",
    "Gihanga",
    "Bugendana",
    "Nyabihanga"
  ],
  "Cabo Verde": [
    "Praia",
    "Mindelo",
    "Santa Maria",
    "Espargos",
    "Assomada",
    "São Filipe",
    "Sal Rei",
    "Tarrafal",
    "Nova Sintra",
    "Praia da Vitória",
    "Ribeira Brava",
    "São Vicente",
    "Brava",
    "Santiago",
    "Boavista",
    "Fogo",
    "Sal",
    "Santo Antão",
    "Maio",
    "Ribeira Grande"
  ],
  "Cambodia": [
    "Phnom Penh",
    "Siem Reap",
    "Battambang",
    "Sihanoukville",
    "Kampong Cham",
    "Kampot",
    "Takeo",
    "Pursat",
    "Kandal",
    "Prey Veng",
    "Kratié",
    "Stung Treng",
    "Ratanakiri",
    "Mondulkiri",
    "Banteay Meanchey",
    "Oddar Meanchey",
    "Koh Kong",
    "Pailin",
    "Svay Rieng",
    "Preah Vihear"
  ],
  "Cameroon": [
    "Yaoundé",
    "Douala",
    "Garoua",
    "Kumba",
    "Bamenda",
    "Bafoussam",
    "Maroua",
    "Nkongsamba",
    "Limbe",
    "Buea",
    "Dschang",
    "Ebolowa",
    "Bafang",
    "Nkambe",
    "Kribi",
    "Mbalmayo",
    "Batibo",
    "Ngaoundéré",
    "Foumban",
    "Buea",
    "Rangoum"
  ],
  "Canada": [
    "Toronto",
    "Vancouver",
    "Montreal",
    "Calgary",
    "Ottawa",
    "Edmonton",
    "Quebec City",
    "Winnipeg",
    "Hamilton",
    "Kitchener",
    "Halifax",
    "London",
    "Victoria",
    "Oshawa",
    "Markham",
    "Brampton",
    "Surrey",
    "Richmond",
    "Burnaby",
    "Saskatoon",
    "Regina",
    "St. John's",
    "Thunder Bay",
    "Chicoutimi",
    "Nanaimo",
    "Lethbridge",
    "Kamloops",
    "Red Deer",
    "Saint-Jean-sur-Richelieu",
    "Abbotsford",
    "Fredericton",
    "Moncton",
    "Saint John",
    "Prince George"
  ],
  "Central African Republic": [
    "Bangui",
    "Bimbo",
    "Berbérati",
    "Mbaïki",
    "Bouar",
    "Kaga Bandoro",
    "Bossangoa",
    "Bangassou",
    "Nola",
    "Sibut",
    "Damara",
    "Carnot",
    "Bozoum",
    "Bria",
    "Alindao",
    "Bangui",
    "Ndele",
    "Ombella-Mpoko",
    "Mongoumba",
    "Kouango"
  ],
  "Chad": [
    "N'Djamena",
    "Moundou",
    "Sarh",
    "Abéché",
    "Kelo",
    "Koutou",
    "Doba",
    "Bongor",
    "Fada N'gourma",
    "Abeche",
    "Mongo",
    "Bongor",
    "Am Timan",
    "N'Djamena",
    "Oum Hadjer",
    "Guelengdeng",
    "Biltine",
    "Pala",
    "Tibesti",
    "Lai",
    "Massebiel"
  ],
  "Chile": [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
    "Antofagasta",
    "Temuco",
    "Rancagua",
    "Arica",
    "Iquique",
    "Puerto Montt",
    "Talca",
    "Viña del Mar",
    "Osorno",
    "Coyhaique",
    "Punta Arenas",
    "Calama",
    "Chillán",
    "Puerto Varas",
    "Rancagua",
    "Curicó",
    "San Antonio",
    "Quillota",
    "Angol",
    "Linares",
    "Copiapó",
    "Ovalle",
    "La Calera",
    "San Fernando",
    "Talcahuano",
    "Dalcahue"
  ],
  "China": [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Hong Kong",
    "Wuhan",
    "Xi'an",
    "Hangzhou",
    "Dongguan",
    "Nanjing",
    "Tianjin",
    "Chongqing",
    "Suzhou",
    "Shijiazhuang",
    "Zhengzhou",
    "Ningbo",
    "Qingdao",
    "Xiamen",
    "Fuzhou",
    "Dalian",
    "Jinan",
    "Changsha",
    "Kunming",
    "Wuxi",
    "Taiyuan",
    "Harbin",
    "Lanzhou",
    "Hefei",
    "Shenzhen",
    "Nanchang"
  ],
  "Colombia": [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Pereira",
    "Santa Marta",
    "Ibagué",
    "Manizales",
    "Valledupar",
    "Soledad",
    "Montería",
    "Sincelejo",
    "Pasto",
    "Tuluá",
    "Popayán",
    "Armenia",
    "Quibdó",
    "Villavicencio",
    "Neiva",
    "Tunja",
    "Leticia",
    "Riohacha",
    "Caldas",
    "Sogamoso",
    "Cali",
    "Yopal",
    "Pasto",
    "Bello"
  ],
  "Comoros": [
    "Moroni",
    "Moutsamoudou",
    "Mitsamiouli",
    "Domoni",
    "Fomboni",
    "Moya",
    "Iconi",
    "Sima",
    "Sambava",
    "Ongoni",
    "Sahani",
    "Ngazidja",
    "Koni-Djodjo",
    "Sima",
    "Mitsamiouli"
  ],
  "Congo, Democratic Republic of the": [
    "Kinshasa",
    "Lubumbashi",
    "Mbuji-Mayi",
    "Kananga",
    "Kisangani",
    "Bukavu",
    "Goma",
    "Tshikapa",
    "Kolwezi",
    "Matadi",
    "Tshumbe",
    "Kikwit",
    "Boma",
    "Uvira",
    "Masina",
    "Mwene-Ditu",
    "Kamina",
    "Inongo",
    "Mbandaka",
    "Mongala",
    "Shaba",
    "Lualaba",
    "Kasai",
    "Sankuru",
    "Haut-Lomami"
  ],
  "Congo, Republic of the": [
    "Brazzaville",
    "Pointe-Noire",
    "Dolisie",
    "Oyo",
    "Owando",
    "Mouyondzi",
    "Lékana",
    "Kinkala",
    "Nganga-Lingui",
    "Kouilou",
    "Makoua",
    "Brazzaville",
    "Sibiti",
    "Tchibanga",
    "Loubomo",
    "Kouilou",
    "Mossendjo",
    "Bétou",
    " Impfondo",
    "Mouyondzi",
    "Djambala"
  ],
  "Costa Rica": [
    "San José",
    "Alajuela",
    "Cartago",
    "Heredia",
    "Liberia",
    "Puntarenas",
    "Limón",
    "Nicoya",
    "Turrialba",
    "San Isidro de El General",
    "Siquirres",
    "Pérez Zeledón",
    "San Carlos",
    "Quepos",
    "San Ramón",
    "Jaco",
    "Guápiles",
    "Carmen",
    "Lajas",
    "La Unión"
  ],
  "Côte d'Ivoire": [
    "Yamoussoukro",
    "Abidjan",
    "Bouaké",
    "San Pedro",
    "Korhogo",
    "Daloa",
    "Yopougon",
    "Abengourou",
    "Man",
    "Bingerville",
    "Sikasso",
    "Divo",
    "Aboisso",
    "Gagnoa",
    "Agboville",
    "Séguéla",
    "Sassandra",
    "Dimbokro",
    "Toumodi",
    "Katiola",
    "Bondoukou"
  ],
  "Croatia": [
    "Zagreb",
    "Split",
    "Rijeka",
    "Osijek",
    "Zadar",
    "Pula",
    "Dubrovnik",
    "Karlovac",
    "Sisak",
    "Slavonski Brod",
    "Varazdin",
    "Bjelovar",
    "Šibenik",
    "Varaždin",
    "Poreč",
    "Samobor",
    "Knin",
    "Trogir",
    "Makarska",
    "Umag"
  ],
  "Cuba": [
    "Havana",
    "Santiago de Cuba",
    "Camagüey",
    "Holguín",
    "Santa Clara",
    "Guantánamo",
    "Las Tunas",
    "Cienfuegos",
    "Pinar del Río",
    "Matanzas",
    "Ciego de Ávila",
    "Sancti Spíritus",
    "Bayamo",
    "Nueva Gerona",
    "Varadero",
    "La Habana Vieja",
    "Trinidad",
    "Sagua la Grande",
    "Santa Cruz del Norte",
    "Jovellanos"
  ],
  "Cyprus": [
    "Nicosia",
    "Limassol",
    "Larnaca",
    "Famagusta",
    "Paphos",
    "Kyrenia",
    "Apoel",
    "Paralimni",
    "Protaras",
    "Agia Napa",
    "Troodos",
    "Kakopetria",
    "Kythrea",
    "Morphou",
    "Deryneia",
    "Lakatamia",
    "Ayios Nikolaos",
    "Karpas Peninsula",
    "Nicosia District",
    "Mesa Geitonia"
  ],
  "Czech Republic": [
    "Prague",
    "Brno",
    "Ostrava",
    "Plzeň",
    "Liberec",
    "Olomouc",
    "Ústí nad Labem",
    "Hradec Králové",
    "Zlin",
    "Pardubice",
    "Jihlava",
    "Karlovy Vary",
    "České Budějovice",
    "Teplice",
    "Kladno",
    "Mladá Boleslav",
    "Chomutov",
    "Most",
    "Havlíčkův Brod",
    "Tábor"
  ],
  "Denmark": [
    "Copenhagen",
    "Aarhus",
    "Odense",
    "Aalborg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Herning",
    "Roskilde",
    "Ballerup",
    "Silkeborg",
    "Frederiksberg",
    "Hillerød",
    "Næstved",
    "Sønderborg",
    "Helsingør",
    "Kalundborg",
    "Skive"
  ],
  "Djibouti": [
    "Djibouti City",
    "Ali Sabieh",
    "Dikhil",
    "Tadjourah",
    "Obock",
    "Diré Daoud",
    "Balbala",
    "Arta",
    "Lake Assal",
    "Dora",
    "Khor Angar",
    "Goubetto",
    "Mouloud",
    "Ali Sabieh",
    "Dikhil",
    "Obock",
    "Tadjourah"
  ],
  "Dominica": [
    "Roseau",
    "Portsmouth",
    "Marigot",
    "Bereavement",
    "Batibou",
    "Calibishie",
    "Castle Bruce",
    "Salisbury",
    "La Plaine",
    "Grand Bay",
    "Good Hope",
    "Wesley",
    "Soufrière",
    "Dublanc",
    "Richards",
    "Bense",
    "Mahaut",
    "Morne Jaune"
  ],
  "Dominican Republic": [
    "Santo Domingo",
    "Santiago",
    "La Romana",
    "San Pedro de Macorís",
    "San Cristóbal",
    "Puerto Plata",
    "Bonao",
    "Moca",
    "Higuey",
    "San Francisco de Macorís",
    "Azua",
    "Barahona",
    "Dajabón",
    "Constanza",
    "Nagua",
    "La Vega",
    "Montecristi",
    "Sabana Grande de Boyá",
    "El Seibo",
    "Valverde"
  ],
  "Ecuador": [
    "Quito",
    "Guayaquil",
    "Cuenca",
    "Santo Domingo",
    "Machala",
    "Manta",
    "Durán",
    "Ambato",
    "Loja",
    "Esmeraldas",
    "Riobamba",
    "Ibarra",
    "Quevedo",
    "El Coca",
    "Babahoyo",
    "La Libertad",
    "Tena",
    "Salinas",
    "Puyo",
    "Otavalo",
    "Naranjal"
  ],
  "Egypt": [
    "Cairo",
    "Alexandria",
    "Giza",
    "Sharm El Sheikh",
    "Hurghada",
    "Luxor",
    "Aswan",
    "Port Said",
    "Suez",
    "Ismailia",
    "Mansoura",
    "Tanta",
    "Fayoum",
    "Damanhur",
    "Beni Suef",
    "Minya",
    "Qena",
    "Sohag",
    "Kafr El Sheikh",
    "Damietta",
    "Sixth of October City"
  ],
  "El Salvador": [
    "San Salvador",
    "Santa Ana",
    "San Miguel",
    "Soyapango",
    "Santa Tecla",
    "Delgado",
    "La Libertad",
    "Apopa",
    "Ilopango",
    "Sonsonate",
    "Ahuachapan",
    "Usulután",
    "La Unión",
    "Rudolph",
    "Zacatecoluca",
    "San Vicente",
    "Coatepeque",
    "Ataco",
    "Chalatenango",
    "El Congo"
  ],
  "Equatorial Guinea": [
    "Malabo",
    "Bata",
    "Ebebiyin",
    "Aconibe",
    "Evinayong",
    "Mongomo",
    "Luba",
    "Annobón",
    "Corisco",
    "Biyang",
    "Ngoya",
    "Cogo",
    "Niefang",
    "Aguacate",
    "Acalayong",
    "Mongomo",
    "Carmen"
  ],
  "Eritrea": [
    "Asmara",
    "Keren",
    "Massawa",
    "Assab",
    "Mendefera",
    "Dahlak",
    "Nakfa",
    "Barentu",
    "Senafe",
    "Agordat",
    "Mekele",
    "Aseb",
    "Ginda",
    "Elabered",
    "Hagaz",
    "Teseney",
    "Adi Quala",
    "Halhal",
    "Akele Guzai"
  ],
  "Estonia": [
    "Asmara",
    "Keren",
    "Massawa",
    "Assab",
    "Mendefera",
    "Dahlak",
    "Nakfa",
    "Barentu",
    "Senafe",
    "Agordat",
    "Mekele",
    "Aseb",
    "Ginda",
    "Elabered",
    "Hagaz",
    "Teseney",
    "Adi Quala",
    "Halhal",
    "Akele Guzai"
  ],
  "Eswatini": [
    "Mbabane",
    "Manzini",
    "Big Bend",
    "Lobamba",
    "Nhlangano",
    "Siteki",
    "Piggs Peak",
    "Hlatikulu",
    "Kwaluseni",
    "Malkerns",
    "Lusoti",
    "Ekwetsembeni",
    "Bhunya",
    "Lindley",
    "Sihhoye",
    "Kukhanyeni",
    "Hlatikhulu"
  ],
  "Ethiopia": [
    "Addis Ababa",
    "Dire Dawa",
    "Mekelle",
    "Gondar",
    "Bahir Dar",
    "Hawassa",
    "Jimma",
    "Debrecin",
    "Dessie",
    "Shashemene",
    "Adama",
    "Sodo",
    "Jijiga",
    "Kombolcha",
    "Gambela",
    "Harar",
    "Arba Minch",
    "Bule Hora",
    "Nekemte",
    "Asella"
  ],
  "Fiji": [
    "Suva",
    "Nadi",
    "Lautoka",
    "Labasa",
    "Ba",
    "Sigatoka",
    "Taveuni",
    "Nasinu",
    "Savusavu",
    "Dreketi",
    "Korolevu",
    "Nausori",
    "Rakiraki",
    "Koro",
    "Yasawa",
    "Levuka",
    "Bala"
  ],
  "Finland": [
    "Helsinki",
    "Espoo",
    "Tampere",
    "Vantaa",
    "Oulu",
    "Turku",
    "Jyvaskyla",
    "Lahti",
    "Kuopio",
    "Pori",
    "Rovaniemi",
    "Kouvola",
    "Joensuu",
    "Hämeenlinna",
    "Porvoo",
    "Lappeenranta",
    "Kemi",
    "Tornio",
    "Seinäjoki",
    "Varkaus"
  ],
  "France": [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Saint-Étienne",
    "Le Havre",
    "Grenoble",
    "Dijon",
    "Nîmes",
    "Aix-en-Provence",
    "Clermont-Ferrand",
    "Angers",
    "Saint-Denis"
  ],
  "Gabon": [
    "Libreville",
    "Port-Gentil",
    "Franceville",
    "Omboué",
    "Mouila",
    "Lambaréné",
    "Lastoursville",
    "Makokou",
    "Tchibanga",
    "Koulamoutou",
    "Bitam",
    "Oyem",
    "Koulamoutou",
    "Lékoni",
    "Kango",
    "Ngounié",
    "Tchibanga"
  ],
  "Gambia": [
    "Banjul",
    "Serekunda",
    "Brikama",
    "Bakau",
    "Kerewan",
    "Kuntaur",
    "Janjanbureh",
    "Mansakonko",
    "Farafenni",
    "Janjanbureh",
    "Basse Santa Su",
    "Serre Kunda",
    "Lamin",
    "Gunjur",
    "Jambanjelly",
    "Kerewan"
  ],
  "Georgia": [
    "Tbilisi",
    "Kutaisi",
    "Batumi",
    "Zugdidi",
    "Rustavi",
    "Zestafoni",
    "Senaki",
    "Gori",
    "Poti",
    "Khashuri",
    "Tqvarchal",
    "Telavi",
    "Akhaltsikhe",
    "Mtskheta",
    "Dusheti",
    "Ozurgeti",
    "Tskaltubo",
    "Ambrolauri",
    "Kvareli",
    "Signagi"
  ],
  "Germany": [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hannover",
    "Nuremberg",
    "Mannheim",
    "Karlsruhe",
    "Freiburg",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen"
  ],
  "Ghana": [
    "Accra",
    "Kumasi",
    "Tamale",
    "Takoradi",
    "Ashaiman",
    "Tema",
    "Cape Coast",
    "Sunyani",
    "Obuasi",
    "Bolgatanga",
    "Wa",
    "Dunkwa-on-Offin",
    "Nkoranza",
    "Akim Oda",
    "Accra",
    "Koforidua",
    "Sekondi",
    "Berekum",
    "Madina",
    "Suhum"
  ],
  "Greece": [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Larissa",
    "Volos",
    "Ioannina",
    "Chania",
    "Kavala",
    "Rhodes",
    "Kalamata",
    "Kozani",
    "Kastoria",
    "Serres",
    "Alexandroupoli",
    "Corinth",
    "Drama",
    "Trikala",
    "Chalkida",
    "Thiva"
  ],
  "Grenada": [
    "St. George's",
    "Gouyave",
    "Grenville",
    "Carriacou",
    "Hillsborough",
    "Victoria",
    "Sauteurs",
    "Morne Rouge",
    "St. David's",
    "L'Anse aux Epines",
    "Birch Grove",
    "Calivigny",
    "St. Mark's"
  ],
  "Guatemala": [
    "Guatemala City",
    "Antigua Guatemala",
    "Quetzaltenango",
    "Escuintla",
    "Santa Cruz del Quiché",
    "Mazatenango",
    "Chimaltenango",
    "Sololá",
    "San Marcos",
    "Zacapa",
    "Puerto Barrios",
    "Retalhuleu",
    "Guastatoya",
    "Coatepeque",
    "Jalapa",
    "Mixco",
    "Villa Nueva",
    "San Juan Sacatepéquez",
    "Villa Canales",
    "Huehuetenango"
  ],
  "Guinea": [
    "Conakry",
    "Kankan",
    "Nzérékoré",
    "Kindia",
    "Labé",
    "Boke",
    "Mamou",
    "Fria",
    "Dalaba",
    "Guéckédou",
    "Kouroussa",
    "Télimélé",
    "Lélouma",
    "Pita",
    "Faranah",
    "Siguiri",
    "Macenta",
    "Dinguiraye",
    "Kissidougou",
    "Coyah"
  ],
  "Guinea-Bissau": [
    "Bissau",
    "Gujarai",
    "Gabú",
    "Bafatá",
    "Mansoa",
    "Canchungo",
    "Bolama",
    "Biombo",
    "Quinhamel",
    "Canchungo",
    "Pirada",
    "Cufar",
    "Farim",
    "Varela",
    "Sao Domingos",
    "Bolama",
    "Catio",
    "Sao Jorge",
    "Colito"
  ],
  "Guyana": [
    "Georgetown",
    "Linden",
    "Bartica",
    "Anna Regina",
    "New Amsterdam",
    "Rosignol",
    "Skeldon",
    "Lusignan",
    "Diamond",
    "Vreed en Hoop",
    "Timehri",
    "Kumaka",
    "Lethem",
    "Port Mourant",
    "Mabaruma",
    "Bamboo Creek",
    "Mahdia",
    "Woodland",
    "Canje",
    "Berbice"
  ],
  "Haiti": [
    "Port-au-Prince",
    "Cap-Haïtien",
    "Jacmel",
    "Les Cayes",
    "Gonaïves",
    "Pétion-Ville",
    "Port-de-Paix",
    "Saint-Marc",
    "Fort-Liberté",
    "Delmas",
    "Les Cayes",
    "Ouanaminthe",
    "Hinche",
    "Miragoâne",
    "Mirebalais",
    "L'Artibonite",
    "Cayes-Jacmel",
    "Jacmel",
    "Limonade",
    "Deschapelles"
  ],
  "Honduras": [
    "Tegucigalpa",
    "San Pedro Sula",
    "Choloma",
    "La Ceiba",
    "El Progreso",
    "Comayagua",
    "Puerto Cortés",
    "Olanchito",
    "Juticalpa",
    "Santa Rosa de Copán",
    "Gracias",
    "Lima",
    "Siguatepeque",
    "Danlí",
    "Nacaome",
    "Tocoa",
    "Yoro",
    "La Lima",
    "Omoa",
    "Dulce Nombre de Culmí"
  ],
  "Hungary": [
    "Budapest",
    "Debrecen",
    "Szeged",
    "Miskolc",
    "Pécs",
    "Győr",
    "Nyíregyháza",
    "Kecskemét",
    "Székesfehérvár",
    "Eger",
    "Kaposvár",
    "Sopron",
    "Békéscsaba",
    "Zalaegerszeg",
    "Veszprém",
    "Salgótarján",
    "Óbuda",
    "Dunaújváros",
    "Budaörs",
    "Szentendre"
  ],
  "Iceland": [
    "Reykjavik",
    "Kopavogur",
    "Hafnarfjordur",
    "Akureyri",
    "Selfoss",
    "Akranes",
    "Vestmannaeyjar",
    "Egilsstadir",
    "Isafjordur",
    "Siglufjordur",
    "Reykjavikurborg",
    "Borgarnes",
    "Vik í Myrdal",
    "Seydisfjordur",
    "Fjardabyggd",
    "Husavik",
    "Skagastrond",
    "Dalvik",
    "Sandgerdi",
    "Grindavik"
  ],
  "India": [
    "New Delhi",
    "Mumbai",
    "Bengaluru",
    "Kolkata",
    "Chennai",
    "Hyderabad",
    "Ahmedabad",
    "Pune",
    "Jaipur",
    "Surat",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Visakhapatnam",
    "Bhopal",
    "Patna",
    "Vadodara",
    "Kochi",
    "Indore",
    "Coimbatore",
    "Agra"
  ],
  "Indonesia": [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
    "Palembang",
    "Makassar",
    "Batam",
    "Malang",
    "Tangerang",
    "Depok",
    "Banjarmasin",
    "Bandar Lampung",
    "Samarinda",
    "Cirebon",
    "Ambon",
    "Yogyakarta",
    "Palu",
    "Mataram",
    "Pontianak"
  ],
  "Iran": [
    "Tehran",
    "Mashhad",
    "Isfahan",
    "Tabriz",
    "Shiraz",
    "Karaj",
    "Ahvaz",
    "Kermanshah",
    "Urmia",
    "Zahedan",
    "Yazd",
    "Rasht",
    "Arak",
    "Qom",
    "Hamadan",
    "Birjand",
    "Gorgan",
    "Kerman",
    "Sari",
    "Bushehr"
  ],
  "Iraq": [
    "Baghdad",
    "Basra",
    "Mosul",
    "Erbil",
    "Sulaymaniyah",
    "Najaf",
    "Karbala",
    "Kirkuk",
    "Duhok",
    "Samawah",
    "Ramadi",
    "Fallujah",
    "Tikrit",
    "Baghdad",
    "Misdar",
    "Hilla",
    "Dhi Qar",
    "Wasit",
    "Al Hillah",
    "An Nasiriyah"
  ],
  "Ireland": [
    "Dublin",
    "Cork",
    "Limerick",
    "Galway",
    "Waterford",
    "Kilkenny",
    "Sligo",
    "Drogheda",
    "Ennis",
    "Tralee",
    "Bray",
    "Malahide",
    "Letterkenny",
    "Athlone",
    "Portlaoise",
    "Naas",
    "Wexford",
    "Killarney",
    "Tullamore",
    "Cavan"
  ],
  "Israel": [
    "Jerusalem",
    "Tel Aviv",
    "Haifa",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Beersheba",
    "Netanya",
    "Holon",
    "Bnei Brak",
    "Ra'anana",
    "Bat Yam",
    "Kfar Saba",
    "Eilat",
    "Herzliya",
    "Modi'in-Maccabim-Re'ut",
    "Nazareth",
    "Tiberias",
    "Afula",
    "Nahariya"
  ],
  "Italy": [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Catania",
    "Venice",
    "Verona",
    "Messina",
    "Padua",
    "Trieste",
    "Taranto",
    "Brescia",
    "Prato",
    "Modena",
    "Reggio Emilia",
    "Livorno"
  ],
  "Jamaica": [
    "Kingston",
    "Montego Bay",
    "Spanish Town",
    "Mandeville",
    "Portmore",
    "Ocho Rios",
    "Negril",
    "Brown's Town",
    "Falmouth",
    "May Pen",
    "Savanna-la-Mar",
    "St. Ann's Bay",
    "Port Antonio",
    "Santa Cruz",
    "Linstead",
    "Morant Bay",
    "Spanish Town",
    "Black River",
    "Old Harbour",
    "Trelawny"
  ],
  "Japan": [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Kobe",
    "Kyoto",
    "Fukuoka",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai",
    "Chiba",
    "Kitakyushu",
    "Kumamoto",
    "Okayama",
    "Sakai",
    "Hamamatsu",
    "Niigata",
    "Nagasaki"
  ],
  "Jordan": [
    "Amman",
    "Zarqa",
    "Irbid",
    "Aqaba",
    "Jerash",
    "Madaba",
    "Salt",
    "Karak",
    "Tafilah",
    "Maan",
    "Ruseifa",
    "Al Ain",
    "Ajloun",
    "Al Karak",
    "As-Salt",
    "Wadi Musa",
    "Sahab",
    "Jafaar",
    "Al Ramtha",
    "Qatrana"
  ],
  "Kazakhstan": [
    "Almaty",
    "Nur-Sultan",
    "Shymkent",
    "Karaganda",
    "Aktobe",
    "Pavlodar",
    "Oskemen",
    "Semey",
    "Taraz",
    "Atyrau",
    "Kostanay",
    "Petropavl",
    "Turkistan",
    "Taldykorgan",
    "Zhanaozen",
    "Ekibastuz",
    "Temirtau",
    "Kyzylorda",
    "Ridder",
    "Stepnogorsk"
  ],
  "Kenya": [
    "Nairobi",
    "Mombasa",
    "Nakuru",
    "Kisumu",
    "Eldoret",
    "Nairobi",
    "Machakos",
    "Nyeri",
    "Meru",
    "Malindi",
    "Lamu",
    "Kitale",
    "Bomet",
    "Embu",
    "Kericho",
    "Isiolo",
    "Garissa",
    "Kakamega",
    "Narok",
    "Nyahururu"
  ],
  "Kiribati": [
    "Tarawa",
    "Betio",
    "Bikenibeu",
    "Teaoraereke",
    "Nanikai",
    "Tanaea",
    "London",
    "Kiritimati",
    "Banaba",
    "Tabiteuea",
    "Makin",
    "Nonouti",
    "Butaritari",
    "Tamana",
    "Tabuaeran",
    "Aranuka",
    "Onotoa",
    "Abemama"
  ],
  "Korea, North": [
    "Pyongyang",
    "Hamhung",
    "Chongjin",
    "Nampo",
    "Wonsan",
    "Sinuiju",
    "Hyesan",
    "Kaesong",
    "Sariwon",
    "Rason",
    "Kanggye",
    "Tokchon",
    "Chunghwa",
    "Sinanju",
    "Kimchaek",
    "Kisong",
    "Pyongsong",
    "Hamhung",
    "Yangdok",
    "Phyongwon"
  ],
  "Korea, South": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Changwon",
    "Seongnam",
    "Goyang",
    "Yongin",
    "Bucheon",
    "Jeju City",
    "Pohang",
    "Gwangmyeong",
    "Siheung",
    "Kimhae",
    "Iksan",
    "Cheongju"
  ],
  "Kosovo": [
    "Pristina",
    "Pec",
    "Mitrovica",
    "Ferizaj",
    "Gjakova",
    "Vushtrri",
    "Suva Reka",
    "Malisheva",
    "Klinë",
    "Djakovica",
    "Lipljan",
    "Obiliq",
    "Gracanica",
    "Gjilan",
    "Dragash",
    "Rahovec",
    "Fushe Kosovo",
    "Shtime",
    "Kamenica",
    "Viti"
  ],
  "Kuwait": [
    "Kuwait City",
    "Hawalli",
    "Salmiya",
    "Farwaniya",
    "Ahmadi",
    "Jahra",
    "Mubarak Al-Kabeer",
    "Sabah Al-Salem",
    "Mangaf",
    "Fahaheel",
    "Adiliya",
    "Wafra",
    "Shuwaikh",
    "Salwa",
    "Abdali",
    "Kuwait International Airport",
    "Jabriya",
    "Khaitan",
    "Rumaithiya",
    "Qurtuba"
  ],
  "Kyrgyzstan": [
    "Bishkek",
    "Osh",
    "Jalal-Abad",
    "Karaganda",
    "Karakol",
    "Naryn",
    "Talas",
    "Batken",
    "Kyzyl-Kiya",
    "Tokmok",
    "Kant",
    "Isfana",
    "Kara-Balta",
    "Karakol",
    "Sokuluk",
    "Tashkent",
    "Chui",
    "Nookat",
    "Cholpon-Ata",
    "Toktogul"
  ],
  "Laos": [
    "Vientiane",
    "Luang Prabang",
    "Pakse",
    "Savannakhet",
    "Vang Vieng",
    "Muang Xai",
    "Thakhek",
    "Xieng Khouang",
    "Bokeo",
    "Luang Namtha",
    "Attapeu",
    "Saravane",
    "Oudomxai",
    "Borikhane",
    "Khammouane",
    "Champasak",
    "Phongsali",
    "Vientiane Prefecture",
    "Sayaboury",
    "Xayaburi"
  ],
  "Latvia": [
    "Riga",
    "Daugavpils",
    "Liepaja",
    "Jurmala",
    "Ventspils",
    "Rēzekne",
    "Jelgava",
    "Riga",
    "Ogre",
    "Rūjiena",
    "Salaspils",
    "Alūksne",
    "Cēsis",
    "Kuldīga",
    "Valmiera",
    "Tukums",
    "Saldus",
    "Bauska",
    "Ludza",
    "Madona"
  ],
  "Lebanon": [
    "Beirut",
    "Tripoli",
    "Sidon",
    "Tyre",
    "Zahle",
    "Jounieh",
    "Byblos",
    "Baalbek",
    "Hermel",
    "Nabatieh",
    "Baabda",
    "Aley",
    "Koura",
    "Batroun",
    "Marjayoun",
    "Bint Jbeil",
    "Choueifat",
    "Keserwan",
    "Metn",
    "Zgharta"
  ],
  "Lesotho": [
    "Maseru",
    "Teyateyaneng",
    "Leribe",
    "Mafeteng",
    "Mohale's Hoek",
    "Berea",
    "Hlotse",
    "Quthing",
    "Qacha's Nek",
    "Leribe",
    "Teyateyaneng",
    "Semonkong",
    "Maputsoe",
    "Mokhotlong",
    "Tsehlanyane",
    "Matatiele",
    "Berea",
    "Ficksburg",
    "Hlotse",
    "Thaba-Tseka"
  ],
  "Liberia": [
    "Monrovia",
    "Gbarnga",
    "Buchanan",
    "Kakata",
    "Harper",
    "Zwedru",
    "Sinoe",
    "Voinjama",
    "Tubmanburg",
    "Bomi Hills",
    "Bong",
    "Margibi",
    "Lofa",
    "Nimba",
    "Grand Bassa",
    "Grand Gedeh",
    "River Cess",
    "Montserrado",
    "Maryland",
    "Gbarpolu"
  ],
  "Libya": [
    "Tripoli",
    "Benghazi",
    "Misrata",
    "Tobruk",
    "Zintan",
    "Sirte",
    "Al Bayda",
    "Sebha",
    "Derna",
    "Khoms",
    "Sabratha",
    "Bani Walid",
    "Ghat",
    "Zawiya",
    "Ajdabiya",
    "Jalo",
    "Murzuq",
    "Nalut",
    "Waddan",
    "Surt"
  ],
  "Liechtenstein": ["Vaduz", "Schaan", "Balzers", "Eschen", "Nendeln", "Mauren", "Schellenberg", "Gamprin", "Ruggell", "Liechtenstein"],
  "Lithuania": [
    "Vilnius",
    "Kaunas",
    "Klaipėda",
    "Šiauliai",
    "Panevėžys",
    "Alytus",
    "Marijampolė",
    "Tauragė",
    "Utena",
    "Telšiai",
    "Visaginas",
    "Jonava",
    "Molėtai",
    "Radviliškis",
    "Kėdainiai",
    "Neringa",
    "Ignalina",
    "Druskininkai",
    "Švenčionys",
    "Daugai"
  ],
  "Luxembourg": [
    "Luxembourg City",
    "Esch-sur-Alzette",
    "Differdange",
    "Dudelange",
    "Echternach",
    "Wiltz",
    "Grevenmacher",
    "Clervaux",
    "Remich",
    "Mersch",
    "Hesperange",
    "Strassen",
    "Kehlen",
    "Rumelange",
    "Bettembourg",
    "Bissen",
    "Rosport",
    "Sanem",
    "Kayl",
    "Howald"
  ],
  "Madagascar": [
    "Antananarivo",
    "Toamasina",
    "Antsiranana",
    "Fianarantsoa",
    "Mahajanga",
    "Toliara",
    "Antananarivo-Avaradrano",
    "Ambatondrazaka",
    "Morondava",
    "Diego Suarez",
    "Tsiroanomandidy",
    "Maroantsetra",
    "Mananjary",
    "Vohibinany",
    "Ankato",
    "Ambanja",
    "Andapa",
    "Ikongo",
    "Ankavandra",
    "Manakara"
  ],
  "Malawi": [
    "Lilongwe",
    "Blantyre",
    "Mzuzu",
    "Zomba",
    "Kasungu",
    "Karonga",
    "Mangochi",
    "Nkhata Bay",
    "Salima",
    "Dedza",
    "Nkhotakota",
    "Chitipa",
    "Rumphi",
    "Ntcheu",
    "Dowa",
    "Phalombe",
    "Mulanje",
    "Nsanje",
    "Balaka",
    "Liwonde"
  ],
  "Malaysia": [
    "Kuala Lumpur",
    "George Town",
    "Johor Bahru",
    "Ipoh",
    "Shah Alam",
    "Kota Kinabalu",
    "Kuching",
    "Malacca City",
    "Petaling Jaya",
    "Alor Setar",
    "Seremban",
    "Kuantan",
    "Sibu",
    "Bintulu",
    "Miri",
    "Sandakan",
    "Batu Pahat",
    "Tawau",
    "Klang",
    "Putrajaya"
  ],
  "Maldives": [
    "Malé",
    "Addu City",
    "F Maldives",
    "Kulhudhuffushi",
    "Thinadhoo",
    "Dhidhdhoo",
    "Naifaru",
    "Kadhdhoo",
    "Thulusdhoo",
    "Gulhi",
    "Hithadhoo",
    "Lh. Naifaru",
    "Malhosandhoo",
    "Kuredhu",
    "Maduvvari",
    "Maafushi",
    "Nellufarhu",
    "Dhigurah",
    "Baa Atoll",
    "Rasdhoo"
  ],
  "Mali": [
    "Bamako",
    "Sikasso",
    "Mopti",
    "Kayes",
    "Tombouctou",
    "Koulikoro",
    "Segou",
    "Gao",
    "San",
    "Kidal",
    "Nioro du Sahel",
    "Markala",
    "Sikasso",
    "Douentza",
    "Koutiala",
    "Bandiagara",
    "Tenenkou",
    "Yorosso",
    "Kolokani",
    "Nara"
  ],
  "Malta": [
    "Valletta",
    "Birkirkara",
    "Sliema",
    "Mosta",
    "Qormi",
    "San Ġwann",
    "Fgura",
    "Zebbug",
    "Hamrun",
    "Gozo",
    "Victoria",
    "Naxxar",
    "St. Paul's Bay",
    "Mġarr",
    "Birżebbuġa",
    "Marsaskala",
    "Rabat",
    "Zurrieq",
    "Vittoriosa",
    "Senglea"
  ],
  "Marshall Islands": [
    "Majuro",
    "Ebeye",
    "Aur",
    "Maloelap",
    "Kili",
    "Kwajalein",
    "Jabor",
    "Wotje",
    "Bikini Atoll",
    "Mili Atoll",
    "Rongelap Atoll",
    "Lae",
    "Ujae",
    "Ailinglaplap",
    "Arno Atoll",
    "Kwajalein Atoll",
    "Maloelap Atoll",
    "Jaluit Atoll",
    "Namorik Atoll",
    "Kili Island"
  ],
  "Mauritania": [
    "Nouakchott",
    "Nouadhibou",
    "Rosso",
    "Kaédi",
    "Kiffa",
    "Atar",
    "Zouérat",
    "Aioun",
    "Selibaby",
    "Timbedra",
    "Moktar",
    "Boutilimit",
    "Bohar",
    "Nema",
    "Aleg",
    "Bir Moghrein",
    "Tidjikja",
    "Ksar",
    "Moudjéria",
    "Kankossa"
  ],
  "Mauritius": [
    "Port Louis",
    "Curepipe",
    "Vacoas-Phoenix",
    "Quatre Bornes",
    "Rose Hill",
    "Beau Bassin-Rose Hill",
    "Savanne",
    "Mahebourg",
    "Black River",
    "Bambous",
    "Goodlands",
    "Belmasset",
    "Triolet",
    "St. Pierre",
    "L'Escalier",
    "Pamplemousses",
    "Plaine Wilhems",
    "Souillac",
    "Rivière du Rempart",
    "Bel Air"
  ],
  "Mexico": [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Cancún",
    "Mérida",
    "Tijuana",
    "León",
    "Querétaro",
    "San Luis Potosí",
    "Córdoba",
    "Veracruz",
    "Hermosillo",
    "Torreón",
    "Chihuahua",
    "Saltillo",
    "Morelia",
    "Aguascalientes",
    "Culiacán",
    "Zacatecas"
  ],
  "Micronesia": [
    "Palikir",
    "Weno",
    "Kolonia",
    "Yap",
    "Chuuk",
    "Pohnpei",
    "Kosrae",
    "Nukufetau",
    "Nukuoro",
    "Mokil",
    "Pingelap",
    "Satawal",
    "Kapingamarangi",
    "Pata",
    "Uman",
    "Satawal",
    "Mapia",
    "Maloelap",
    "Takaeu",
    "Woleai"
  ],
  "Moldova": [
    "Chișinău",
    "Bălți",
    "Bender",
    "Tiraspol",
    "Rîbnița",
    "Cahul",
    "Orhei",
    "Soroca",
    "Florești",
    "Căușeni",
    "Nisporeni",
    "Hîncești",
    "Fălești",
    "Strășeni",
    "Ștefan Vodă",
    "Ungheni",
    "Sîngerei",
    "Comrat",
    "Cahul",
    "Taraclia"
  ],
  "Monaco": ["Monaco", "Monte Carlo", "La Condamine", "Moneghetti", "Fontvieille", "Monaco-Ville", "Beausoleil", "Cap d'Ail"],
  "Mongolia": [
    "Ulaanbaatar",
    "Erdenet",
    "Darkhan",
    "Choibalsan",
    "Mörön",
    "Hovd",
    "Baganuur",
    "Khovd",
    "Sükhbaatar",
    "Bulgan",
    "Zuunmod",
    "Ölgii",
    "Tsetserleg",
    "Bayankhongor",
    "Arvaikheer",
    "Ulaangom",
    "Sharyn Gol",
    "Sukhbaatar",
    "Mandalgovi",
    "Hentii"
  ],
  "Montenegro": [
    "Podgorica",
    "Nikšić",
    "Herceg Novi",
    "Bijelo Polje",
    "Tivat",
    "Bar",
    "Kotor",
    "Rožaje",
    "Pljevlja",
    "Berane",
    "Ulcinj",
    "Mojkovac",
    "Budva",
    "Kolasin",
    "Petnjica",
    "Gusinje",
    "Andrijevica",
    "Cetinje",
    "Žabljak",
    "Plav"
  ],
  "Morocco": [
    "Rabat",
    "Casablanca",
    "Marrakech",
    "Fes",
    "Tangier",
    "Agadir",
    "Oujda",
    "Kenitra",
    "Temara",
    "Meknes",
    "Settat",
    "El Jadida",
    "Tétouan",
    "Nador",
    "Khouribga",
    "Beni Mellal",
    "Safi",
    "Safi",
    "Al Hoceima",
    "Azilal"
  ],
  "Mozambique": [
    "Maputo",
    "Beira",
    "Nampula",
    "Nacala",
    "Tete",
    "Pemba",
    "Chimoio",
    "Quelimane",
    "Inhambane",
    "Xai-Xai",
    "Tete",
    "Lichinga",
    "Manica",
    "Dondo",
    "Maxixe",
    "Marracuene",
    "Angoche",
    "Chokwe",
    "Cuamba",
    "Nhamatanda"
  ],
  "Myanmar (Burma)": [
    "Naypyidaw",
    "Yangon",
    "Mandalay",
    "Mawlamyine",
    "Bago",
    "Taunggyi",
    "Myitkyina",
    "Sagaing",
    "Pathein",
    "Kawthoung",
    "Sittwe",
    "Lashio",
    "Hakha",
    "Naypyidaw",
    "Kyaukphyu",
    "Hpa-An",
    "Phuket",
    "Dawei",
    "Shwebo",
    "Monywa"
  ],
  "Namibia": [
    "Windhoek",
    "Swakopmund",
    "Walvis Bay",
    "Oshakati",
    "Rundu",
    "Katima Mulilo",
    "Lüderitz",
    "Keetmanshoop",
    "Tsumeb",
    "Otjiwarongo",
    "Henties Bay",
    "Opuwo",
    "Outjo",
    "Gobabis",
    "Namibia",
    "Mariental",
    "Usakos",
    "Damaraland",
    "Khorixas",
    "Arandis"
  ],
  "Nauru": ["Yaren", "Meneng", "Nauru", "Boe", "Buada", "Anibare", "Nauru Island"],
  "Nepal": [
    "Kathmandu",
    "Pokhara",
    "Lalitpur",
    "Bhaktapur",
    "Biratnagar",
    "Janakpur",
    "Butwal",
    "Nepalgunj",
    "Dhangadhi",
    "Hetauda",
    "Birgunj",
    "Itahari",
    "Bhadrapur",
    "Bhimeshwar",
    "Rajbiraj",
    "Kirtipur",
    "Sindhulimadi",
    "Madhyapur Thimi",
    "Gorkha",
    "Ramechhap"
  ],
  "Netherlands": [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Tilburg",
    "Almere",
    "Breda",
    "Nijmegen",
    "Haarlem",
    "Arnhem",
    "Zaanstad",
    "Apeldoorn",
    "Amersfoort",
    "Dordrecht",
    "Leiden",
    "Emmen",
    "Venlo",
    "Spijkenisse"
  ],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Napier-Hastings",
    "Dunedin",
    "Palmerston North",
    "Rotorua",
    "New Plymouth",
    "Invercargill",
    "Whangarei",
    "Nelson",
    "Gisborne",
    "Timaru",
    "Blenheim",
    "Upper Hutt",
    "Lower Hutt",
    "Masterton",
    "Tokoroa"
  ],
  "Nicaragua": [
    "Managua",
    "León",
    "Granada",
    "Masaya",
    "Chinandega",
    "Matagalpa",
    "Estelí",
    "Bluefields",
    "Rivas",
    "Jinotepe",
    "Diriamba",
    "Carazo",
    "Somoto",
    "Nandaime",
    "El Viejo",
    "Boaco",
    "Ocotal",
    "San Carlos",
    "Camatagua",
    "Ticuantepe"
  ],
  "Niger": [
    "Niamey",
    "Zinder",
    "Maradi",
    "Tahoua",
    "Agadez",
    "Diffa",
    "Dosso",
    "Birni N'Konni",
    "Tillabéri",
    "N'guigmi",
    "Ayorou",
    "Say",
    "Niamey",
    "Filingue",
    "Tibiri",
    "Kollo",
    "Bouza",
    "Madaoua",
    "Gouré",
    "Magaria"
  ],
  "Nigeria": [
    "Abuja",
    "Lagos",
    "Port Harcourt",
    "Ibadan",
    "Kano",
    "Benin City",
    "Jos",
    "Ilorin",
    "Enugu",
    "Owerri",
    "Kaduna",
    "Ikeja",
    "Maiduguri",
    "Calabar",
    "Warri",
    "Abakaliki",
    "Abeokuta",
    "Sokoto",
    "Onitsha",
    "Zaria"
  ],
  "North Macedonia": [
    "Skopje",
    "Bitola",
    "Kumanovo",
    "Ohrid",
    "Prilep",
    "Tetovo",
    "Veles",
    "Strumica",
    "Shtip",
    "Kavadarci",
    "Ohrid",
    "Gevgelija",
    "Debar",
    "Resen",
    "Kriva Palanka",
    "Radovish",
    "Makedonska Kamenica",
    "Valandovo",
    "Negotino",
    "Bogdanci"
  ],
  "Norway": [
    "Oslo",
    "Bergen",
    "Stavanger",
    "Drammen",
    "Kristiansand",
    "Fredrikstad",
    "Porsgrunn",
    "Skien",
    "Ålesund",
    "Sandnes",
    "Bodø",
    "Haugesund",
    "Molde",
    "Tromsø",
    "Sarpsborg",
    "Gjøvik",
    "Lillehammer",
    "Halden",
    "Arendal",
    "Narvik"
  ],
  "Oman": [
    "Muscat",
    "Salalah",
    "Sohar",
    "Nizwa",
    "Sur",
    "Barka",
    "Musandam",
    "Ibri",
    "Suwaiq",
    "Dhofar",
    "Salalah",
    "Al Buraimi",
    "Al Rustaq",
    "Tanuf",
    "Fahal",
    "Bidbid",
    "Al Wusta",
    "Dakhiliyah",
    "Al Mudhaybi",
    "Mahal"
  ],
  "Pakistan": [
    "Islamabad",
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Peshawar",
    "Quetta",
    "Gujranwala",
    "Sialkot",
    "Hyderabad",
    "Islamabad",
    "Abbottabad",
    "Sukkur",
    "Bahawalpur",
    "Larkana",
    "Mardan",
    "Nawabshah",
    "Dera Ghazi Khan",
    "Jhelum"
  ],
  "Palau": ["Ngerulmud", "Koror", "Melekeok", "Airai", "Ngaraard", "Ngatpang", "Peleliu", "Sonsorol", "Kayangel", "Hatohobei"],
  "Panama": [
    "Panama City",
    "Colón",
    "David",
    "Santiago",
    "Chitré",
    "La Chorrera",
    "Penonomé",
    "Aguadulce",
    "Bocas del Toro",
    "El Porvenir",
    "San Miguelito",
    "Puerto Armuelles",
    "Sona",
    "Las Tablas",
    "Changuinola",
    "Veraguas",
    "Balboa",
    "Arraiján",
    "Cerro Punta",
    "Coclé"
  ],
  "Papua New Guinea": [
    "Port Moresby",
    "Lae",
    "Mount Hagen",
    "Madang",
    "Rabaul",
    "Goroka",
    "Wewak",
    "Kokopo",
    "Kimbe",
    "Buka",
    "Popondetta",
    "Arawa",
    "Kavieng",
    "Tabubil",
    "Laiagam",
    "Tari",
    "Vanimo",
    "Kerema",
    "Chimbu",
    "Oro Bay"
  ],
  "Paraguay": [
    "Asunción",
    "Ciudad del Este",
    "Encarnación",
    "Pedro Juan Caballero",
    "Concepción",
    "San Lorenzo",
    "Luque",
    "Fernando de la Mora",
    "Capiatá",
    "Lambare",
    "Villarrica",
    "Itauguá",
    "Hernandarias",
    "Paraguari",
    "Caaguazú",
    "San Pedro",
    "Areguá",
    "Altos",
    "Carapeguá",
    "Caazapá"
  ],
  "Peru": [
    "Lima",
    "Arequipa",
    "Trujillo",
    "Callao",
    "Cusco",
    "Piura",
    "Chiclayo",
    "Iquitos",
    "Huancayo",
    "Puno",
    "Ayacucho",
    "Tacna",
    "Juliaca",
    "Chimbote",
    "Ica",
    "Loreto",
    "Huánuco",
    "Cajamarca",
    "Moyobamba",
    "Tumbes"
  ],
  "Philippines": [
    "Manila",
    "Quezon City",
    "Cebu City",
    "Davao City",
    "Zamboanga City",
    "Antipolo",
    "Iloilo City",
    "General Santos",
    "Taguig",
    "Pasig",
    "Makati",
    "Bacoor",
    "Caloocan",
    "Malabon",
    "San Juan",
    "Las Piñas",
    "Muntinlupa",
    "Marikina",
    "Pasay",
    "Puerto Princesa"
  ],
  "Poland": [
    "Warsaw",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Katowice",
    "Białystok",
    "Gdynia",
    "Czestochowa",
    "Radom",
    "Sosnowiec",
    "Toruń",
    "Zabrze",
    "Gliwice",
    "Olsztyn",
    "Rzeszów"
  ],
  "Portugal": [
    "Lisbon",
    "Porto",
    "Amadora",
    "Braga",
    "Coimbra",
    "Setúbal",
    "Aveiro",
    "Évora",
    "Vila Nova de Gaia",
    "Leiria",
    "Guimarães",
    "Funchal",
    "Ponta Delgada",
    "Cascais",
    "Tavira",
    "Albufeira",
    "Sintra",
    "Viseu",
    "Oeiras",
    "Beja"
  ],
  "Qatar": ["Doha", "Al Rayyan", "Al Wakrah", "Umm Salal", "Dukhan"],
  "Romania": [
    "Doha",
    "Al Rayyan",
    "Al Wakrah",
    "Umm Salal",
    "Al Khor",
    "Mesaieed",
    "Al Daayen",
    "Al Sheehaniya",
    "Qatar City",
    "Madinat ash Shamal",
    "Lusail",
    "Al Thakhira",
    "Wakif",
    "Madinat ash Shamal",
    "Al Ghuwairiya"
  ],
  "Russia": [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Nizhny Novgorod",
    "Kazan",
    "Chelyabinsk",
    "Samara",
    "Omsk",
    "Rostov-on-Don",
    "Ufa",
    "Volgograd",
    "Krasnoyarsk",
    "Voronezh",
    "Saratov",
    "Tolyatti",
    "Izhevsk",
    "Barnaul",
    "Krasnodar",
    "Tyumen"
  ],
  "Rwanda": [
    "Kigali",
    "Butare",
    "Gisenyi",
    "Musanze",
    "Ruhengeri",
    "Kibungo",
    "Nyagatare",
    "Huye",
    "Nyanza",
    "Rwamagana",
    "Gikondo",
    "Kirehe",
    "Burera",
    "Ngoma",
    "Rubavu",
    "Gasabo",
    "Muhanga",
    "Kamonyi",
    "Nyamagabe",
    "Ngororero"
  ],
  "Saint Kitts and Nevis": [
    "Basseterre",
    "Charlestown",
    "Sandy Point Town",
    "Tabernacle",
    "Cayon",
    "Dieppe Bay Town",
    "Mackey's Estate",
    "Cotton Ground",
    "Bricklyn",
    "St. Paul's"
  ],
  "Saint Lucia": [
    "Castries",
    "Soufrière",
    "Vieux Fort",
    "Gros Islet",
    "Rodney Bay",
    "Anse La Raye",
    "Bonaire",
    "Canaries",
    "Dennery",
    "Micoud",
    "Laborie",
    "Ti Rocher",
    "Marigot Bay",
    "Cas en Bas",
    "Desruisseaux"
  ],
  "Saint Vincent and the Grenadines": [
    "Kingstown",
    "Villa",
    "Calliaqua",
    "Barrouallie",
    "Bequia",
    "Argyle",
    "Mesopotamia",
    "Chateaubelair",
    "Georgetown",
    "Layou",
    "Ratho Mill",
    "Richmond",
    "South Rivers",
    "Camden Park",
    "Kingstown Park"
  ],
  "Samoa": [
    "Apia",
    "A'ana",
    "Faleolo",
    "Savaii",
    "Lautoka",
    "Vaitele",
    "Saleimoa",
    "Lalomanu",
    "Leone",
    "Sataua",
    "Fagali'i",
    "Salelologa",
    "Mulifanua",
    "Faleasiu",
    "Fagafau"
  ],
  "San Marino": [
    "San Marino",
    "Serravalle",
    "Bellinzona",
    "Borgo Maggiore",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Chiesanuova",
    "Montegiardino",
    "San Leo",
    "Città di San Marino"
  ],
  "Sao Tome and Principe": [
    "São Tomé",
    "Principe",
    "Neves",
    "Santa Catarina",
    "Santana",
    "São João dos Angolares",
    "Trindade",
    "Angra do Heroísmo",
    "Ribera Grande",
    "São Tomé Island"
  ],
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Khobar",
    "Dhahran",
    "Tabuk",
    "Khamis Mushait",
    "Buraidah",
    "Abha",
    "Najran",
    "Hafar al-Batin",
    "Al Ahsa",
    "Yanbu",
    "Jubail",
    "Arar",
    "Al Qassim",
    "Al Majma'ah",
    "Al Ula"
  ],
  "Senegal": [
    "Dakar",
    "Touba",
    "Pikine",
    "Saint-Louis",
    "Kaolack",
    "Ziguinchor",
    "Thiès",
    "Mbour",
    "Kaffrine",
    "Fatick",
    "Diourbel",
    "Tambacounda",
    "Kedougou",
    "Sedhiou",
    "Bargny",
    "Guédiawaye",
    "Rufisque",
    "Lugle",
    "Mbacké",
    "Kolda"
  ],
  "Serbia": [
    "Belgrade",
    "Novi Sad",
    "Niš",
    "Kragujevac",
    "Subotica",
    "Zrenjanin",
    "Leskovac",
    "Valjevo",
    "Senta",
    "Šabac",
    "Kikinda",
    "Vranje",
    "Pančevo",
    "Smederevo",
    "Apatin",
    "Čačak",
    "Prokuplje",
    "Ruma",
    "Bečej",
    "Banjaluka"
  ],
  "Seychelles": [
    "Victoria",
    "Beau Vallon",
    "Anse Royale",
    "La Digue",
    "Praslin",
    "Anse Boileau",
    "Baie Sainte Anne",
    "Glacis",
    "Pointe Larue",
    "Takamaka",
    "Moutya",
    "Souris Island",
    "Mahé Island",
    "Curieuse Island",
    "Cousin Island"
  ],
  "Sierra Leone": [
    "Freetown",
    "Bo",
    "Kenema",
    "Makeni",
    "Kabala",
    "Lungi",
    "Port Loko",
    "Koidu",
    "Pujehun",
    "Bonthe",
    "Moyamba",
    "Tonkolili",
    "Kambia",
    "Western Area",
    "Bombali"
  ],
  "Singapore": [
    "Singapore City",
    "Jurong East",
    "Bedok",
    "Tampines",
    "Bukit Batok",
    "Woodlands",
    "Yishun",
    "Sengkang",
    "Hougang",
    "Punggol",
    "Toa Payoh",
    "Ang Mo Kio",
    "Queenstown",
    "Clementi",
    "Serangoon",
    "Bishan",
    "Downtown Core",
    "Novena",
    "Tiong Bahru",
    "Geylang"
  ],
  "Slovakia": [
    "Bratislava",
    "Košice",
    "Prešov",
    "Nitra",
    "Trnava",
    "Zvolen",
    "Martin",
    "Trenčín",
    "Poprad",
    "Nové Zámky",
    "Banská Bystrica",
    "Handlová",
    "Púchov",
    "Hlohovec",
    "Malacky",
    "Levice",
    "Partizánske",
    "Prievidza",
    "Sereď",
    "Ružomberok"
  ],
  "Slovenia": [
    "Ljubljana",
    "Maribor",
    "Celje",
    "Kranj",
    "Velenje",
    "Nova Gorica",
    "Trbovlje",
    "Koper",
    "Slovenj Gradec",
    "Domžale",
    "Bled",
    "Ptuj",
    "Kamnik",
    "Ajdovščina",
    "Škofja Loka",
    "Murska Sobota",
    "Piran",
    "Grosuplje",
    "Ravne na Koroškem",
    "Metlika"
  ],
  "Solomon Islands": [
    "Honiara",
    "Gizo",
    "Auki",
    "Lata",
    "Noro",
    "Munda",
    "Buala",
    "Taro",
    "Tulagi",
    "Rabaul",
    "Kavieng",
    "Kira Kira",
    "Malaita",
    "Marau",
    "Owaraha",
    "Rendova",
    "Santa Isabel",
    "Shortland Islands",
    "Western Province",
    "Choiseul"
  ],
  "Somalia": [
    "Mogadishu",
    "Hargeisa",
    "Bosaso",
    "Kismayo",
    "Baidoa",
    "Galkayo",
    "Jowhar",
    "Burao",
    "Las Anod",
    "Berbera",
    "Merca",
    "Garoowe",
    "Dhusamareb",
    "Qardho",
    "Afgoye",
    "Kandala",
    "Eyl",
    "Jawhar",
    "Bardera",
    "Taleh"
  ],
  "South Africa": [
    "Pretoria",
    "Cape Town",
    "Johannesburg",
    "Durban",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Nelson Mandela Bay",
    "Tshwane",
    "Polokwane",
    "Mbombela",
    "Kimberley",
    "Pietermaritzburg",
    "Boksburg",
    "Soweto",
    "Vereeniging",
    "Richards Bay",
    "George",
    "Uitenhage",
    "Upington"
  ],
  "South Sudan": [
    "Juba",
    "Wau",
    "Malakal",
    "Bor",
    "Aweil",
    "Rumbek",
    "Yei",
    "Nimule",
    "Kapoeta",
    "Pibor",
    "Bentiu",
    "Terekeka",
    "Tombura",
    "Yambio",
    "Akobo",
    "Cueibet",
    "Mayom",
    "Terekeka",
    "Jonglei",
    "Gbudue"
  ],
  "Spain": [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Malaga",
    "Murcia",
    "Palma de Mallorca",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Granada",
    "Valladolid",
    "San Sebastián",
    "La Coruna",
    "Oviedo",
    "Gijón",
    "Salamanca",
    "Pamplona",
    "Almeria"
  ],
  "Sri Lanka": [
    "Colombo",
    "Kandy",
    "Galle",
    "Jaffna",
    "Negombo",
    "Anuradhapura",
    "Matara",
    "Batticaloa",
    "Trincomalee",
    "Ratnapura",
    "Nuwara Eliya",
    "Kurunegala",
    "Kalutara",
    "Vavuniya",
    "Kegalle",
    "Gampaha",
    "Dambulla",
    "Puttalam",
    "Hambantota",
    "Mullaitivu"
  ],
  "Sudan": [
    "Khartoum",
    "Omdurman",
    "Port Sudan",
    "Nyala",
    "El Obeid",
    "Kassala",
    "Wad Madani",
    "Kosti",
    "Juba",
    "Al-Fashir",
    "Atbara",
    "El Geneina",
    "Sennar",
    "Dongola",
    "Damazin",
    "Merowe",
    "Zalingei",
    "Abu Hamad",
    "Birket Al Awamer",
    "Rabak"
  ],
  "Suriname": [
    "Paramaribo",
    "Wanica",
    "Nickerie",
    "Brokopondo",
    "Saramacca",
    "Coronie",
    "Commewijne",
    "Marowijne",
    "Sipaliwini",
    "Para",
    "Albina",
    "Domburg",
    "Lelydorp",
    "Moengo",
    "Patterson",
    "Nieuw Nickerie",
    "Saint Laurent du Maroni",
    "Blaka Watra",
    "Boven Corantijn",
    "Kabalebo"
  ],
  "Sweden": [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Linköping",
    "Västerås",
    "Örebro",
    "Helsingborg",
    "Jönköping",
    "Norrköping",
    "Lund",
    "Umeå",
    "Gävle",
    "Borås",
    "Trollhättan",
    "Sundsvall",
    "Karlstad",
    "Eskilstuna",
    "Mölndal",
    "Luleå"
  ],
  "Switzerland": [
    "Bern",
    "Zurich",
    "Geneva",
    "Basel",
    "Lausanne",
    "Lucerne",
    "St. Gallen",
    "Lugano",
    "Biel/Bienne",
    "Thun",
    "Winterthur",
    "Neuchâtel",
    "Zug",
    "Kriens",
    "Fribourg",
    "Schaffhausen",
    "Bellinzona",
    "La Chaux-de-Fonds",
    "Sion",
    "Yverdon-les-Bains"
  ],
  "Syria": [
    "Damascus",
    "Aleppo",
    "Homs",
    "Latakia",
    "Hama",
    "Tartus",
    "Deir ez-Zor",
    "Raqqa",
    "Idlib",
    "Qamishli",
    "Hasakah",
    "Daraa",
    "Sweida",
    "Banias",
    "Al-Hasakah",
    "Palmyra",
    "Manbij",
    "Ariha",
    "Darayya",
    "Zabadani"
  ],
  "Tajikistan": [
    "Dushanbe",
    "Khujand",
    "Kulob",
    "Bokhtar",
    "Istaravshan",
    "Qurgonteppa",
    "Gissar",
    "Vahdat",
    "Khorugh",
    "Isfara",
    "Tursunzoda",
    "Rudaki",
    "Jirgatol",
    "Darvoz",
    "Penjikent",
    "Yovon",
    "Kanibadam",
    "Ayni",
    "Sughda",
    "Shahrinav"
  ],
  "Tanzania": [
    "Dodoma",
    "Dar es Salaam",
    "Arusha",
    "Mwanza",
    "Mbeya",
    "Tanga",
    "Kilimanjaro",
    "Zanzibar City",
    "Morogoro",
    "Mtwara",
    "Pemba",
    "Tabora",
    "Kigoma",
    "Iringa",
    "Rukwa",
    "Shinyanga",
    "Singida",
    "Ruvuma",
    "Manyara",
    "Lindi"
  ],
  "Thailand": [
    "Bangkok",
    "Chiang Mai",
    "Pattaya",
    "Nakhon Ratchasima",
    "Khon Kaen",
    "Hat Yai",
    "Udon Thani",
    "Chiang Rai",
    "Nakhon Si Thammarat",
    "Samut Prakan",
    "Surat Thani",
    "Ratchaburi",
    "Nakhon Sawan",
    "Lampang",
    "Ayutthaya",
    "Rayong",
    "Sukhothai",
    "Phuket",
    "Krabi",
    "Trang"
  ],
  "Togo": [
    "Lomé",
    "Kara",
    "Sokodé",
    "Tsévié",
    "Atakpamé",
    "Kpalimé",
    "Tchamba",
    "Dapaong",
    "Bassar",
    "Aného",
    "Aneho",
    "Notsé",
    "Kétao",
    "Pagouda",
    "Nukafu",
    "Mango",
    "Adéta",
    "Togoville",
    "Hahotoé",
    "Kozah"
  ],
  "Tonga": [
    "Nukualofa",
    "Neiafu",
    "Ha'apai",
    "Tonga Town",
    "Motu'a",
    "Lapaha",
    "Vava'u",
    "Koloa",
    "Haveluloto",
    "Tefisi",
    "‘Eua",
    "Ofoa",
    "Niuatoputapu",
    "Fua'amotu",
    "Niuatā"
  ],
  "Trinidad and Tobago": [
    "Port of Spain",
    "San Fernando",
    "Scarborough",
    "Chaguanas",
    "Arima",
    "Tobago",
    "Princes Town",
    "Pointe-a-Pierre",
    "Couva",
    "Diego Martin",
    "Siparia",
    "Woodbrook",
    "St. Augustine",
    "Guanapo",
    "Marabella",
    "Point Fortin",
    "Tacarigua",
    "La Romaine",
    "St. Joseph",
    "Mayaro"
  ],
  "Tunisia": [
    "Tunis",
    "Sfax",
    "Sousse",
    "Ariana",
    "Gabès",
    "Kairouan",
    "Bizerte",
    "La Marsa",
    "Nabeul",
    "Kasserine",
    "Sidi Bouzid",
    "Monastir",
    "Zaghouan",
    "Medenine",
    "Mahdia",
    "Beja",
    "Gafsa",
    "Tozeur",
    "Kebili",
    "Tataouine"
  ],
  "Turkey": [
    "Ankara",
    "Istanbul",
    "Izmir",
    "Bursa",
    "Antalya",
    "Adana",
    "Konya",
    "Gaziantep",
    "Mersin",
    "Kayseri",
    "Eskisehir",
    "Sakarya",
    "Diyarbakır",
    "Kahramanmaraş",
    "Tekirdağ",
    "Manisa",
    "Trabzon",
    "Aydin",
    "Ordu",
    "Samsun"
  ],
  "Turkmenistan": [
    "Ashgabat",
    "Turkmenbashi",
    "Mary",
    "Dashoguz",
    "Balkanabat",
    "Köneürgenç",
    "Tejen",
    "Gazanjyk",
    "Merv",
    "Baharden",
    "Gökdepe",
    "Serdar",
    "Kaka",
    "Leba",
    "Yylanly",
    "Seydi",
    "Buzmeyin",
    "Abadan",
    "Sakarchaga",
    "Anau"
  ],
  "Tuvalu": ["Funafuti", "Fakaofo", "Nukufetau", "Nukulaelae", "Vaitupu", "Nanumanga", "Niutao", "Tuvalu"],
  "Uganda": [
    "Kampala",
    "Entebbe",
    "Mukono",
    "Jinja",
    "Mbale",
    "Mbarara",
    "Gulu",
    "Masaka",
    "Fort Portal",
    "Kabale",
    "Kasese",
    "Arua",
    "Lira",
    "Soroti",
    "Hoima",
    "Nansana",
    "Buwama",
    "Kitgum",
    "Kiryandongo",
    "Iganga"
  ],
  "Ukraine": [
    "Kyiv",
    "Kharkiv",
    "Odesa",
    "Dnipro",
    "Donetsk",
    "Lviv",
    "Zaporizhzhia",
    "Kryvyi Rih",
    "Mykolaiv",
    "Sevastopol",
    "Mariupol",
    "Luhansk",
    "Simferopol",
    "Chernihiv",
    "Poltava",
    "Ivano-Frankivsk",
    "Khmelnytskyi",
    "Chernivtsi",
    "Ternopil",
    "Zhytomyr"
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Dubai",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm Al-Quwain",
    "Al Ain",
    "Dibba Al-Fujairah",
    "Khalifa City",
    "Hatta",
    "Al Ain",
    "Luwaisah",
    "Madinat Zayed",
    "Jebel Ali",
    "Masfout",
    "Al Wagan",
    "Al Faqa",
    "Ghayathi",
    "Silah"
  ],
  "United Kingdom": [
    "London",
    "Birmingham",
    "Manchester",
    "Glasgow",
    "Liverpool",
    "Leeds",
    "Newcastle upon Tyne",
    "Sheffield",
    "Bristol",
    "Cardiff",
    "Edinburgh",
    "Coventry",
    "Nottingham",
    "Kingston upon Hull",
    "Stoke-on-Trent",
    "Wolverhampton",
    "Plymouth",
    "Southampton",
    "Brighton and Hove",
    "Aberdeen",
    "Belfast"
  ],
  "United States": [
    "New York City",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "San Francisco",
    "Charlotte",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington, D.C.",
    "Boston"
  ],
  "Uruguay": [
    "Montevideo",
    "Salto",
    "Paysandú",
    "Las Piedras",
    "Rivera",
    "Tacuarembó",
    "Maldonado",
    "Durazno",
    "Cerro Largo",
    "Colonia del Sacramento",
    "Artigas",
    "San José de Mayo",
    "Florida",
    "San Carlos",
    "Punta del Este",
    "Lascano",
    "Treinta y Tres",
    "Atlántida",
    "Dolores",
    "Young"
  ],
  "Uzbekistan": [
    "Tashkent",
    "Samarkand",
    "Bukhara",
    "Namangan",
    "Andijan",
    "Nukus",
    "Ferghana",
    "Khiva",
    "Termez",
    "Sirdaryo",
    "Jizzakh",
    "Navai",
    "Kokand",
    "Margilan",
    "Uchkuduk",
    "Chirchik",
    "Gulistan",
    "Angren",
    "Zarafshan",
    "Yangiyul"
  ],
  "Vanuatu": [
    "Port Vila",
    "Luganville",
    "Espiritu Santo",
    "Tanna",
    "Malekula",
    "Pentecost",
    "Ambae",
    "Epi",
    "Erromango",
    "Aniwa",
    "Atauro",
    "Futuna",
    "Malo",
    "Mota Lava",
    "Norsup",
    "Sola"
  ],
  "Vatican City": ["Vatican City"],
  "Venezuela": [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Ciudad Guayana",
    "La Guaira",
    "Maturín",
    "Porlamar",
    "San Cristóbal",
    "Merida",
    "Barinas",
    "Puerto La Cruz",
    "Cumana",
    "Lechería",
    "Punto Fijo",
    "Los Teques",
    "Trujillo",
    "Acarigua",
    "Guanare",
    "El Tigre"
  ],
  "Vietnam": [
    "Hanoi",
    "Ho Chi Minh City",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Nha Trang",
    "Hue",
    "Vinh",
    "Nam Dinh",
    "Bac Ninh",
    "Thanh Hoa",
    "Haiphong",
    "Long Xuyen",
    "Rach Gia",
    "Quy Nhon",
    "Thai Nguyen",
    "Cam Ranh",
    "My Tho",
    "Ha Long",
    "Phan Thiet"
  ],
  "Yemen": [
    "Sana'a",
    "Aden",
    "Taiz",
    "Al Hudaydah",
    "Ibb",
    "Dhamar",
    "Al Mukalla",
    "Hajjah",
    "Sa'dah",
    "Marib",
    "Amran",
    "Al Bayda",
    "Al Jawf",
    "Lahij",
    "Raymah",
    "Al Mahwit",
    "Hadramaut",
    "Shabwa",
    "Al Maharah",
    "Socotra"
  ],
  "Zambia": [
    "Lusaka",
    "Ndola",
    "Kitwe",
    "Livingstone",
    "Luanshya",
    "Chipata",
    "Kabwe",
    "Mufulira",
    "Chingola",
    "Mazabuka",
    "Monze",
    "Kasama",
    "Pemba",
    "Solwezi",
    "Lunte",
    "Chililabombwe",
    "Siavonga",
    "Serenje",
    "Mpika",
    "Kawambwa"
  ],
  "Zimbabwe": [
    "Harare",
    "Bulawayo",
    "Chitungwiza",
    "Mutare",
    "Gweru",
    "Kwekwe",
    "Kadoma",
    "Masvingo",
    "Victoria Falls",
    "Marondera",
    "Beitbridge",
    "Chegutu",
    "Shurugwi",
    "Rusape",
    "Kariba",
    "Bulawayo",
    "Chipinge",
    "Hwange",
    "Nyanga",
    "Seke"
  ]
};
